### ISSUE TITLE
[Draft] vue 문서만들기

### ISSUE THREAD

**Issue by arch-spatula** [arch-spatula/arch-spatula.github.io#186]
# 글쓰기 주제

```
doc/vue
```

---

- [x] 학습자료 추가
- [x] 문서만들기

## 참고할 자료

- https://joshua1988.github.io/vuejs/
- https://joshua1988.github.io/vue-camp/textbook.html

**Comment by arch-spatula** [comment]
https://test-utils.vuejs.org/

위 vue 테스트 문서를 추가해야 합니다.

**Comment by arch-spatula** [comment]
vue를 CLI로 제어하는 방법을 추가해야 합니다.

**Comment by arch-spatula** [comment]
https://simplevue.gitbook.io/intro/

vue 튜토리얼문서 추가하기

**Comment by arch-spatula** [comment]
https://cli.vuejs.org/

vue CLI 문서

**Comment by arch-spatula** [comment]
생성

```sh
npm install -g @vue/cli
```

삭제

```sh
npm uninstall -g @vue/cli
```

**Comment by arch-spatula** [comment]
vite을 통해 설치하는 것이 더 안정적입니다.

**Comment by Jake-kim-sang-hyun** [comment]
https://vueuse.org/guide/best-practice.html

위 라이브러리 추가해주세요
